# version: '3.7'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build: 
      context: ./requirements/mariadb 
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    depends_on:
      - wordpress 
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/akatfi/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/akatfi/data/mariadb'


networks:
  inception:
    name: inception
    driver: bridge